CREATE DATABASE IF NOT EXISTS ad;
USE ad;

DROP TABLE IF EXISTS `items`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `locations`;
DROP TABLE IF EXISTS `buy_prices`;
DROP TABLE IF EXISTS `bids`;
DROP TABLE IF EXISTS `bidders`;
DROP TABLE IF EXISTS `sellers`;